# This is a config for E2B sandbox template.
# You can use template ID (j8lh5kqpbf7zuic5giaz) or template name (vibe-nextjs-takhur-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-takhur-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-takhur-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-takhur-2')

team_id = "92658cf3-f7f0-40d5-b625-05b0474c7fa2"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-takhur-2"
template_id = "j8lh5kqpbf7zuic5giaz"
